spring.application.name=AppFinance

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/appfinance}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT configuration
jwt.secret=${JWT_SECRET}

# Server Port
server.port=${SERVER_PORT:8081}
